### PR TITLE
Merge pull request #3 from krishna4040/master

### PR DESCRIPTION
**Pull request by karanBRAVO**
pull request

### CODE REVIEW

**Comment by karanBRAVO** [comment]
I have updated the frontend code and dashboard will be updated soon.
## Merge my code.🧑‍🎓

**Comment by krishna4040** [comment]
had you pulled my commits before creating the pr?

**Comment by krishna4040** [comment]
i am merging this change please refer to the previous commits i made to backend and pull the commits onto your local project

**Comment by karanBRAVO** [comment]
I have already pulled them.🦄

**Comment by karanBRAVO** [comment]
I have not added the content in the **_About us_** page send me the content what to add in it. That should/will contain everything about the project. It just has the heading, image and social media links.

**Pull request merged**
